import './globals.sass'
import type { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): React.JSX.Element {
  return (
    <html lang="en">
      <body className='w-screen h-screen flex justify-center items-center'>
        {children}
      </body>
    </html>
  )
}
